name: vIcmAr Auto-Post

on:
  schedule:
    - cron: '0 * * * *' # Esto corre el bot CADA HORA
  workflow_dispatch: # Esto te permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permisos necesarios para que el bot pueda subir la base de datos
    permissions:
      contents: write

    steps:
      - name: Descargando repositorio
        uses: actions/checkout@v3

      - name: Configurando Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Actualizado para evitar el warning de Google API

      - name: Instalando librerías
        run: |
          pip install feedparser google-generativeai google-auth-oauthlib google-api-python-client requests groq flask

      - name: Ejecutando vIcmAr
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: python index.py

      - name: Guardar cambios en DB
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar base de datos de noticias [skip ci]"
          file_pattern: "*.db"
          commit_user_name: "Bot Noticias"
          commit_user_email: "actions@github.com"
          push_options: '--force'
          skip_dirty_check: false
          branch: main
